### ISSUE TITLE
Why no npm package?

### ISSUE THREAD

**Issue by TimDaub** [johanholmerin/rollup-plugin-workers#2]
Hey,

I was wondering why your package isn't registered in npm. Please let me know.

**Comment by johanholmerin** [comment]
It's one more step with no real value added. At the moment it's also unclear what the future of npm and Github Packages are. But if you want, I can publish it to npm.

**Comment by TimDaub** [comment]
Thanks for the quick response.

> It's one more step with no real value added.

I ended up using another package. For me, it's valuable when it's on npm. Though, I agree with you that there's lots of uncertainty. Thx for ur help.

**Comment by hughrawlinson** [comment]
Just chiming in to say that I would love an npm package. I can't imagine that npm will go away any time soon, regardless of the acquisition - so much infrastructure is built on it.

I had a look at another package, but my use case is for Audio Worklets, and it seems like this is the one that supports those.

**Comment by johanholmerin** [comment]
Published as rollup-plugin-workers

**Comment by hughrawlinson** [comment]
Thank you!
