### ISSUE TITLE
Consider support for newer rullup versions

### ISSUE THREAD

**Issue by Exoridus** [johanholmerin/rollup-plugin-workers#4]
`emitChunk` is marked as deprecated. When using your plugin with the latest rollup version (`2.61.1`), a deprecation warning pops up, which states that `emitFile` should be used instead of `emitChunk` which is marked as deprecated.

**Comment by johanholmerin** [comment]
I've updated the code to use the new methods. Could you try out the changes from the repo before I publish to npm, to verify that everything works?

**Comment by Exoridus** [comment]
It seems now to be working fine, thanks!

**Comment by johanholmerin** [comment]
Published as 2.1.0
