### ISSUE TITLE
compatibility issues with @rollup/plugin-json and @rollup/plugin-node-resolve

### ISSUE THREAD

**Issue by SArpnt** [johanholmerin/rollup-plugin-workers#5]
in [this commit](https://github.com/SArpnt/bytebeat-composer/tree/546474310f2e143ca108fb5f19663163c5c4095d) if the worker plugin is loaded before json, the json doesn't include correctly.

if the plugin is enabled at all the plugin has-a typeerror
```
[!] (plugin worker) TypeError: Cannot read properties of undefined (reading 'match')
node_modules/@codemirror/view/dist/index.js
```

(node and rollup setup is in the rollup folder)

**Comment by johanholmerin** [comment]
Could you try with 2.1.1 and see if the issue remains?

**Comment by SArpnt** [comment]
plugin still has issues when loaded before the json plugin but the node resolve issue is solved

**Comment by johanholmerin** [comment]
If you are including JSON files you'll need to prevent the plugin from running on those files, using the normal rollup convention: `worker({ exclude: '**/*.json' })`
